language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.0
before_install:
- pod install --project-directory=Example
script:
- set -eo pipefail
- xcodebuild test -workspace Example/BeamAPI.xcworkspace -scheme BeamAPI-Example -sdk iphonesimulator
- pod lib lint --allow-warnings --verbose
